version: "3"
services:
    typescript:
        container_name: typescript
        build:
            context: .
            dockerfile: ./typescript/Dockerfile
        volumes:
            - ./:/usr/src/app
        ports:
            - '63205:22'