version: "3.1"
services:
    db:
        image: mariadb
        restart: always
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=example
            - MYSQL_USER=example
            - MYSQL_PASSWORD=example

    treefrog:
        build: treefrog